package com.auth.backend.controllers;

import com.auth.backend.repositories.DayRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import com.auth.backend.repositories.UserRepository;
import com.auth.backend.models.User;
import com.auth.backend.models.Day;

import javax.validation.Valid;

@Controller // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private DayRepository dayRepository;

    @PostMapping(path = "/add")
    public @ResponseBody User createNote( @RequestBody User note) {
        userRepository.save(note);
        return note;
    }
    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/days")
    public @ResponseBody Iterable<Day> getAllDays() {
        return dayRepository.findAll();
    }
}